version: '3.8'

services:
  gtasks-front:
    image: gtasks-front
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
